update script

diff --git a/problem-download b/problem-download
--- a/problem-download
+++ b/problem-download
@@ -1,32 +1,45 @@
 #!/bin/bash -x
-./api-snapshot-list > snapshot
-if [ -e "./problem" ]; then
+if [ -e "./problems" ]; then
 a=$(cat snapshot | jq -r '.snapshots[] | .snapshot_hash ' | tail -n 1)
 b=$(cat lasthash)
 if [ "$a" == "$b" ]; then
   echo "Same snapshots"
+  exit 0
 fi
-#./api-blob $a > problems.json
+
+
+echo "update problems.json"
+./api-blob $a > problems.json
+ret_code=$?
+if [ $ret_code != 0 ]; then
+  echo "Failed to download problems.json"
+  exit 1
+fi
+
+
 
 function download() {
   id=$1
   h=$(echo $2 | sed -e "s/'//g")
-  while true; do
-    ./api-blob ${h} > problems/${id}.txt
+  if [ -e "problems/${id}.txt" ]; then
+    echo "Problem $id is already downloaded."
+  else
+    while true; do
+    ./api-blob ${h} > "problems/${id}.txt"
     ret_code=$?
     if [ $ret_code != 0 ]; then
-      echo "Download retry after sleep"
+      echo "wait for retry.."
       sleep 5
     else
       break
     fi
-  done
+    done
+  fi
 }
 
 cat problems.json | jq -r ".problems[] | [.problem_id, .problem_spec_hash] | @sh" | while read line; do
-  echo $line
   download $line
 done
 
-echo $b > lasthash
+echo $a > "lasthash"
 fi
